variables:
  DOCKER_IMAGE: 'docker.cdek.ru/nodenx-dev-rocky9:latest'

stages:
  - lint
  - publish

.common:
  image: ${DOCKER_IMAGE}

  cache:
    key: vue-ui-kit-vendor
    paths:
      - node_modules/

  tags:
    - docker

yarn:
  stage: .pre
  extends: .common

  script:
    - yarn install

  cache:
    policy: push

lint:
  stage: lint
  extends: .common

  script:
    - yarn run lint:cli

  cache:
    policy: pull

test:
  stage: lint
  extends: .common

  script:
    - yarn run test:cli

  cache:
    policy: pull

type-check:
  stage: lint
  extends: .common

  script:
    - yarn run type-check

  cache:
    policy: pull

publish:
  stage: publish
  extends: .common
  only:
    - main
  when: manual

  script:
    - yarn build
    - npm publish
